### ISSUE TITLE
How Do I Run The App For The First Time?

### ISSUE THREAD

**Issue by kwsg97** [SecretsX/Venus#1]
How can i run it? How i can use this?

**Comment by NotCookey** [comment]
> How can i run it? How i can use this?

You can simply download the compiled binaries from releases or by clicking here [Releases](https://github.com/SecretsX/Venus/releases). Select the latest release thats availabel and download the `Venus.zip` file.

After downloading just extract it using 7zip or Winrar and run the Venus.exe file. If you're running for the first time the application will take around 30 seconds for first startup. And soon you can see a clock widget on your desktop feel free to use the source code and modify it as you please <3
